{% set total = pag.nextPage %}
{% if total > 1 %}
{% set next = pag.nextPage %}
{% set prev = pag.prevPage %}

<div class="text-center">
    <ul class="pagination">
        {%if ! pag.prevPage | null%}
            {# previous page #}
            {%buffer href%}{%exec str_replace '-_page_-', prev, url%}{%endbuffer%}
            <li class="prev">{%exec Html::link href, 'Anterior', 'title="Ir a la pág. anterior"' %}</li>
        {% else %}
            <li class="prev  disabled"><a title="Ir a la pág. anterior" href="#">Anterior</a></li>
        {%endif%}

        {% if ! pag.nextPage | null %}
            {%buffer href%}{%exec str_replace '-_page_-', next, url%}{%endbuffer%}
            <li class="prev">{% exec Html::link href, 'Siguiente', 'title="Ir a la pág. siguiente" class="nextprev"' %}</li>
        {% else %}
            <li class="prev disabled"><a title="Ir a la pág. siguiente" href="#">Siguiente</a></li>
        {% endif %}
    </ul>
</div>
{%endif%}