<h4><?php echo $s_caption;?></h4>
<ul class="file">
<?php foreach($a_data as $o_val):?>
	<li>
	<div class="center">
	<?php echo Html::img("mime/$o_val->type.png", array('title' => $o_val->name,
		'alt' => $o_val->type)
	);?>
	<div class="noflow"><?php echo $o_val->name?></div>
	<div class="options">
	<?php
		echo Html::link("private/files/info{$o_val->$s_id}",
			'<span class="icon-info-sign"></span>',
			array('class'=>'btn', 'title' => __('Info'))
		);
		echo Html::link("private/files/delete{$o_val->$s_id}",
			'<span class="icon-remove"></span>',
			array('class'=>'btn', 'title' => __('Remove'))
		);
	if($o_val->isdir):
		echo Html::link("private/files/download{$o_val->$s_id}",
		 '<span class="icon-download-alt"></span>',
		array('class' => 'btn'));
	else:
		echo Html::link("private/files{$o_val->$s_id}",
			'<span class="icon-download-alt"></span>',
			array('class'=>'btn', 'title' => __('Download'))
		);
	endif;?>
	</div>
	</div>
</li>
<?php endforeach?>	
</ul>
<hr />
