<h3><?php echo __('More');?></h3>
<?php echo Html::link('alt/rss', Html::img('more/rss.png'))?>&nbsp;
<?php if(!empty($twitter)):?>
<a href="http://twitter.com/<?php echo $twitter;?>">
<?php echo Html::img('more/twitter.png')?></a>&nbsp;
<?php endif;?>

<?php if(!empty($facebook)):?>
<a href="http://facebook.com/<?php echo $facebook;?>">
<?php echo Html::img('more/facebook.png')?>&nbsp;
</a>
<?php endif;?>
