<div id="sharedbar">
<a href="http://twitter.com/share" class="twitter-share-button" data-count="horizontal" data-via="aberroteran" data-lang="es">Tweet</a><script type="text/javascript" src="http://platform.twitter.com/widgets.js" async="async"></script>
<script type="text/javascript" src="http://widgets.digg.com/buttons.js" async="async"></script><a class="DiggThisButton  DiggCompact" href="http://digg.com/submit?style=no"></a>
<iframe src="http://www.facebook.com/plugins/like.php?href=<?php echo $canonical?>&amp;send=true&amp;layout=button_count&amp;width=300&amp;show_faces=false&amp;action=recommend&amp;colorscheme=light&amp;font&amp;height=21" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:300px; height:21px;" allowTransparency="true"></iframe>
</div>
