{%extends  'admin.phtml' %}
{%block content %}
{%exec Flash::content %}
<style>
    input.no-border{
        border-color: transparent;
    }

    input.title{
        text-align: center;
        font-size: 200%;
        font-weight: bold;
        height: auto;
    }
</style>
<div class="row">
    <div class="col-10 offset-1">
        {%exec Form::open%}
        {%exec Form::select 'posts.post_type_id', sel,'class="control"', NULL, 'Type Publish'%}
		{%exec Form::text 'posts.title' 'class="control no-border title" placehold="Title"' %}
        <div id="rendered-markdown"></div>
		<div class="entry-markdown-content">
        {%exec Form::textarea 'posts.content' 'class="control entry-markdown"' %}
        </div>
        {%inline '_partial/submit.phtml'%}
        {%exec Form::close%}
    </div>
</div>
{%endblock%}
{% block jsblock%}
    {%js 'zepto.min' %}
    {%js 'marked'%}
<script type="text/javascript">
'use strict';
$(function(){
    var editor = $('#posts_content'), render = $('#rendered-markdown'),
        cb = function(){
            var text = editor.val();
            render.html(marked(text));
            render.css({display: 'block'});
            editor.css({display: 'none'});
            editor.height(render.height());
        }
    ;
    render.click(function(){
        editor.css({display: 'block'});
        render.css({display: 'none'});
        editor.focus();
    });

    editor.blur(cb);
    $(cb);
});
</script>
{%endblock%}

