{%extends  'default.phtml' %}
{%block content %}
<div id="list" class="row">
	{% inline "_partial/paginator.phtml" %}
	{% for i in pag %}
	<section class="col-4">
        <div class="post">
		<header>
            {% buffer uri %}index/post/{{i.strid}}{% endbuffer %}
            <h2 class="t-post">{%exec Html::link uri i.title%}</h2>
            <div class="info">
    			<img src="{%exec BlogUtil::image i.content %}" />
    			<div class="calendar">
    				<span class="c-day">{{i.modified_in|date_f:'d'}}</span>
    				<span class="c-year">
    					<i class="fa fa-calendar-o"></i> {{i.modified_in|date_f:'Y'}}
    				</span>
    				{{i.modified_in|date_f:'M'}}
    			</div>
            </div>
		</header>
		{% autoescape off %}{%exec BlogUtil::trucate i.content 150 %}{% endautoescape %}
        </div>
	</section>
	{%endfor%}
	
</div>
{% inline "_partial/paginator.phtml" %}
{%endblock%}