<!DOCTYPE html>
<html>
<head>
<?php Tag::css("bootstrap/bootstrap.min") ?>
<?php Tag::css("$style/style") ?>
<?php echo Html::includeCss() ?>
<?php if(isset($canonical)):?>
	<link rel="canonical" href="<?php echo  $canonical?>" />
<?php endif?>
<?php if(isset($keyword)):?>
	<meta name="keywords" content="<?php echo $keyword?>" />
<?php endif;?>
<title><?php echo $ptitle; ?> - <?php echo $title?></title>
<meta http-equiv="content-type" content="application/xhtml+xml; charset=UTF-8" />
</head>
<body>
<div id="wrap">
	<div id="header" class="row-fluid">
		<h1 id="logo" class="span6"><?php echo $title;?></h1>
		<h2 id="slogan" class="span6"><?php echo $desc;?></h2>
	</div>
	<div id="menu"><?php View::partial('menu');?></div>
	<div id="content" class="container">
	<div class="span9"><?php View::content(); ?></div>
	<div class="span3"><?php View::partial('sidebar');?></div>
</div>
<div id="footer"><p><?php echo $footer;?><br />
Powered By <a href="https://github.com/Ashrey/Kuword/">KuWord</a> |
	Style by <a href="http://www.styleshout.com/">styleshout</a>|
	<?php echo Html::link('feed/tl', '(RSS)');?></p>
</div>
<?php
echo Tcode::exec(Places::get('closebody'));
Tag::js('jquery.min');
echo Html::includeJs();
?>
</body>
</html>
