<!DOCTYPE html>
<html>
<head>
{% k "Tag::css" "bootstrap/bootstrap.min" %}
{% k "Tag::css" style %}
{% k "Html::includeCss"%} 
{% if canonical %}
	<link rel="canonical" href="{{canonical}}" />
{% endif %}
<title>{{ptitle}} - {{title}}</title>
<meta http-equiv="content-type" content="application/xhtml+xml; charset=UTF-8" />
</head>
<body>
<div id="wrap">
	<div id="header" class="row-fluid">
		<h1 id="logo" class="span6">{{title}}</h1>
		<h2 id="slogan" class="span6">{{desc}}</h2>
	</div>
	<div id="menu">{% partial  "nav" %}</div>
	<div id="content" class="container">
	<h1>{{ptitle}}</h1>
	<div class="span9"> {% block content %}{% endblock %}</div>
	<div class="span3"><?php View::partial('sidebar');?></div>
</div>
<div id="footer"><p>{{footer}}<br />
Powered By <a href="https://github.com/Ashrey/Kuword/">KuWord</a> |
	Style by <a href="http://www.styleshout.com/">styleshout</a>|
	{%k "Html::link" 'feed/tl'  '(RSS)' %}</p>
	</div>
</body>
</html>
