<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="es">
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<?php Tag::css("bootstrap/bootstrap.min") ?>
<?php echo Html::includeCss() ?>
<title><?php echo $ptitle?></title>
</head>
<body>
<div class="container">
	<header>
		<?php View::partial('private/menu');?>
	</header>
	<div id="content"><?php View::content()?></div>
	<?php Tag::js('jquery.min')?>
	<?php Tag::js('tinymce/tinymce.min')?>
	<?php echo Html::includeJs()?>
<script type="text/javascript">
tinymce.init({
    selector: "textarea",
        plugins: [
        "advlist autolink lists link image  preview anchor",
        "searchreplace visualblocks code",
        "insertdatetime media table contextmenu paste"
    ]
 });
</script>

</div>
</body>
</html>
