<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="es">
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
{% exec Tag::css "admin/style" %}
{% exec 'Html::includeCss'%}
<title>{{ptitle}}</title>
</head>
<body>
<div class="container">
	<header>
		{% partial 'menu' %}
	</header>
	<div id="content">{% block content%}{%endblock%}</div>
	{%exec Html::includeJs %}
</div>
</body>
</html>
