<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="es">
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
{% exec 'Tag::css' "bootstrap/bootstrap.min" %}
{% exec 'Html::includeCss'%}
<title>{{ptitle}}</title>
</head>
<body>
<div class="container">
	<header>
		{% partial 'menu' %}
	</header>
	<div id="content">{% block content%}{%endblock%}</div>
	{%exec Tag::js 'jquery.min' %}
	{%exec Tag::js 'tinymce/tinymce.min'%}
	{%exec Html::includeJs %}
<script type="text/javascript">
tinymce.init({
    selector: "textarea",
        plugins: [
        "advlist autolink lists link image  preview anchor",
        "searchreplace visualblocks code",
        "insertdatetime media table contextmenu paste"
    ]
 });
</script>
</div>
</body>
</html>
