<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="es">
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
{%css "admin/style" %}
<title>{{ptitle}}</title>
</head>
<body class="container">
	<header>
		<h1>{{title}}</h1> {% inline '_partial/menu.phtml' %}
	</header>
	<div id="content">{% block content%}{%endblock%}</div>
</body>
{% block jsblock%}{%endblock%}
</html>
