<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="es">
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
{%css "admin/style" %}
{%css style %}
<title>{{ptitle}}</title>
</head>
<body>
	<header class="navbar">
		{% inline '_partial/menu.phtml' %}
	</header>
	<div id="content" class="container">{% block content%}{%endblock%}</div>
</body>
{% block jsblock%}{%endblock%}
</html>
