<!DOCTYPE html>
<html>
<head>
{%css "admin" %}
{%css "basic" %}
{%css style %}
{% if canonical %}
	<link rel="canonical" href="{{canonical}}" />
{% endif %}
<title>{{title}}</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
</head>
<body>
    {% block header %}
	<header class="row" id="top">
		<h1 id="logo" class="col-6">{{pagename}}</h1>
		<h2 id="slogan" class="col-6">{{pagedesc}}</h2>
	</header>
    {% endblock %}

    {% block menu %}
	   <div id="menu">{% inline  "_partial/nav.phtml" %}</div>
    {% endblock %}

	<div class="container">
		<h1>{{ptitle}}</h1>
        <div class="row">
		    <div class="col-12">{% block content %}{% endblock %}</div>
        </div>
	</div>

    <footer class="text-center"><p>{{footer}}<br />
    Powered By <a href="https://github.com/Ashrey/Kuword/">KuWord</a> |
    	Style by <a href="http://www.styleshout.com/">styleshout</a>|
    	{%exec Html::link 'feed/tl'  '(RSS)' %}</p>
    </footer>
    {% block jsblock%}{%endblock%}
</body>
</html>
