<!DOCTYPE html>
<html>
<head>
{%css "admin" %}
{%css "basic" %}
{%css style %}
{% if canonical %}
	<link rel="canonical" href="{{canonical}}" />
{% endif %}
<title>{{ptitle}} - {{title}}</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
</head>
<body>
	<header class="row" id="top">
		<h1 id="logo" class="col-6">{{title}}</h1>
		<h2 id="slogan" class="col-6">{{desc}}</h2>
	</header>

	<div id="menu">{% inline  "_partial/nav.phtml" %}</div>

	<divclass="container">
		<h1>{{ptitle}}</h1>
        <div class="row">
		    <div class="offset-1 col-10"> {% block content %}{% endblock %}</div>
        </div>
	</div>

    <footer class="text-center"><p>{{footer}}<br />
    Powered By <a href="https://github.com/Ashrey/Kuword/">KuWord</a> |
    	Style by <a href="http://www.styleshout.com/">styleshout</a>|
    	{%exec Html::link 'feed/tl'  '(RSS)' %}</p>
    </footer>
</body>
</html>
