<div class="page-header">
    <h1>{{title}}</h1>
</div>
<div class="row">
     {% if result %}
        <div class="span8 offset2">
		    {%exec Input::isAjax as ajax%}
            {% if NOT ajax %}
                <div class="btn-group text-center">
                    {%exec Html::LinkAction 'create' 'Crear <i class="icon-plus"></i>' ' class="btn btn-primary"' %}
                    {%exec Html::LinkAction "editar/$result->id", 'Editar <i class="icon-edit"></i>', ' class="btn btn-warning"' %}
                    {%exec Html::LinkAction "borrar/$result->id", 'Borrar <i class="icon-remove"></i>', ' class="btn btn-danger js-confirm" title="Está seguro?"' %}
                    {%exec Html::LinkAction '' 'Listar  <i class="icon-list"></i>' 'class="btn btn-info"' %}
                </div>
            {% endif%}
            <dl class="dl-horizontal">
                {% for  i in cols %}
                    <dt>{{result.alias[i]}}</dt>
                    <dd>{%exec ModelForm::fieldValue i, result%}</dd>
                {% endfor %}
            </dl>
         </div>
    {% else %}
        {%exec header "HTTP/1.0 404 Not Found" %}
        <div class="span4 offset4">
            <div class="alert alert-block alert-danger">
                No se ha encontrado el registro buscado
            </div>
        </div>
    {% endif %}
</div>
